#!/bin/bash

if [ $# -ne 1 ]; then
  echo "Error: Please provide a URL as an argument" >&2
  exit 1
fi

url="$1"

temp_file=$(mktemp /tmp/measurepage.XXXXXX)

wget -q -O "$temp_file" "$url"

if [ $? -eq 0 ]; then
  ./wordcount -w < "$temp_file"
else
  echo 0
fi

rm "$temp_file"

exit 0
